### PR TITLE
Vagrant setup

### PR DESCRIPTION
**Pull request by Lbatson**
added Vagrantfile and setup.sh for automated dev environment setup. updated readme.md with info about using it.

### CODE REVIEW

**Comment by Lbatson** [comment]
leaving as separate branch

**Comment by raylu** [comment]
to elaborate:
1. I'm not sure having your env set up for you is a good idea in the first place. Yes, there are a lot of tools to help people write code while being blissfully unaware of how anything works, but I don't really endorse that thinking.
2. It's weird you started with a really old Ubuntu that didn't have python3.3, pulled it in, then installed all the deps as root. I would prefer if you started with a less ancient OS and followed the README.

**Comment by Lbatson** [comment]
Ok, well i'll expand on my reasoning a bit.
1. Sure providing the development environment does shortcut part of the learning process if the process is concerned with actually teaching that as well. Part of the reason I included it was to give those who didn't want to bother with setting up a development environment on their own and install the required pieces just to start developing on the site an easier option. Again it's only and option and they can still go about setting it all up themselves but I think it also exposes them to other things as well such as automating development environments, writing scripts to set them up, etc. I don't see much wrong with incorporating it in to the project though and I don't see that it would detract from any part of a learning experience.
2. Ubuntu 12.04 64-bit is sort of the standard default instance that gets provided as a sane default for many hosts, environments etc. It is a long term release and I wouldn't say terribly outdated since it will have support until 2017 and numerous support articles and forum topics. Vagrant also provides this as their default working version to use so I feel it's better to go with a working standard than to be worried about cutting edge especially since everything can still work. As for installing dependencies as root, well I don't feel this matters too much in this case considering the environment is just for local development of this project only through the vm but it could be set up without root as well. I didn't feel a need to use a virtualenv because of this and the entire OS and setup is really only to be used for this project.

I'll keep the branch and continue using it this way myself but I think maybe consider it just as another option especially for those wanting to quickly start contributing.

**Comment by raylu** [comment]
2) The next LTS comes out [in 18 days](https://wiki.ubuntu.com/TrustyTahr/ReleaseSchedule). We're using (what was until very recently) a cutting edge python, so it absolutely makes sense to worry about cutting edge. A venv (not virtualenv) is still better than installing as root if we're concerned about teaching best practices (and being able to edit package sources more easily).

**Comment by Lbatson** [comment]
It doesn't matter as everything can be installed and again you must have missed the point of the matter about using a standard distribution provided by the development system tools. If Vagrant releases a default image under the new LTS release then no problem switching to that. Also plenty of people still use 12.04 and there's abundant information/resources out there for it. 

I guess no further comments about point 1 and the legitimacy of this being a valid option for a development environment is to mean there isn't much of a reason not to incorporate this into the project.

I think the overall point of this project is to encourage development on the site. Providing a default setup that allows people to do that makes sense. For those that want to dive into it a bit more and set up all of the requirements themselves, then they will. I'm not discouraging this simply providing an option, which people can also learn from.

The length of this conversation over something that simply is a non issue is not fostering support nor contribution to the project. The goal is to a.) have a working site people will use but also b.) provide something people can work on. The mere fact that I've provided another option for them to do so and have met such resistance seems to me more of a nitpick and rigid stance for the mere sake of wanting to only do things a certain way as opposed to being open and accommodating. I don't see how this is going to provide an environment that others will want to work in and contribute to and discourages those that do.

**Comment by chancez** [comment]
Many people run an OS which makes installation of all the dependencies listed here difficult to install (Windows, even OSX). Installing into a Vagrant environment makes a lot of sense I think. Or at least having the option.

**Pull request closed without merging**
