### PR TITLE
IRC Nickname

### LINKED ISSUE #9: Add `nickname` to `users` table.
Just for people like me who use different names in IRC vs. GitHub, it would be nice to have the optional ability to add a nickname to show beside/under your username either in your account or in the /users view.

### PR DESCRIPTION
**Pull request by ZachMassia**
Closes #9

### CODE REVIEW

**Comment by raylu** [comment]
just tried this out. everything seems to work, but it's unclear that anything happened. either some sort of positive status indicator next to the button, some sort of curtain-style top bar thingy, or just sticking the refresh back in would be nice

also, if the enter button worked too (preferably by changing the form-inline from a div to a form and handling its `submit` event)

**Comment by raylu** [comment]
did a partial merge with rewrites at 1147c01

**Comment by ZachMassia** [comment]
I should be able to get this finished up by this evening. 

You said you wanted the form to work without JS, but as it is now, the server returns `JSON` when you  `POST` to `/account/contact_info`. 

How would you want me to proceed here?

From what I can tell, my options are:
- Modify `set_email` to work for both `contact_type`s (JS)
- Send a redirect argument with the `POST`, and `set_email` can stay unchanged (No JS)
- Modify the handler to always redirect, and remove the `location.reload` call from `set_email` (No JS)

**Comment by raylu** [comment]
oh, right.... let's go with option 1.

3 wouldn't work because redirecting an ajax request doesn't redirect the browser

**Comment by ZachMassia** [comment]
Is there anything else that needs to be done on this, @raylu?

Did you want me to try and clean up the commits, or are you able to do that when you merge?

**Comment by raylu** [comment]
squashed with f0e2dc3, minor fix at 498507e

**Pull request closed without merging**
